# Generated by Django 6.0.3 on 2026-04-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
