# Generated by Django 6.0.2 on 2026-04-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_instructor_contact_number_and_more'),
        ('student_dash', '0002_alter_document_upload_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Revision', 'Need Revision'), ('Rejected', 'Rejected')], max_length=20)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.instructor')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_dash.thesis')),
            ],
        ),
    ]
