# Generated by Django 6.0.2 on 2026-04-05 14:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE PROFESSOR', 'Associate Professor'), ('ASSISTANT PROFESSOR', 'Assistant Professor'), ('INSTRUCTOR', 'Instructor')], max_length=19)),
                ('qualification', models.CharField(max_length=255)),
                ('contact_number', models.CharField(verbose_name=14)),
                ('email', models.CharField(verbose_name=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='deputy1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy1_department', to='department.instructor'),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy2_department', to='department.instructor'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_department', to='department.instructor'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('batch', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.student')),
            ],
        ),
    ]
