# Generated by Django 6.0.1 on 2026-04-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='contact_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
